### ISSUE TITLE
Stuck on "Loading voyage details"

### ISSUE THREAD

**Issue by FortKnox1337** [IAmPicard/STTVoyage#2]
Logs in, but is not able to load anything. Crew tab works just not the Voyage tab.

**Comment by IAmPicard** [comment]
It's been a long time since I updated this, but just published a [new release](https://github.com/IAmPicard/STTVoyage/releases/tag/v0.1.6). Can you give it a try and let me know if you still see the problem?

**Comment by FortKnox1337** [comment]
Sorry for delay in responding. It loads up okay and and tabs all work now.

I had to uninstall the old one first though and installing as a fresh install as installing it over the old one just causes it to crash.

**Comment by IAmPicard** [comment]
Thanks
